apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view
  namespace: dev
rules:
- apiGroups:
  - ""
  resourceNames:
  - "*"
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
