repositories:
  - name: nginx-stable
    url: https://helm.nginx.com/stable
  - name: cert-manager
    url: https://charts.jetstack.io 
  - name: harbor
    url: https://helm.goharbor.io

---
releases:
  - name: cert-manager
    namespace: cert-manager
    createNamespace: true
    chart: jetstack/cert-manager
    version: 1.8.0
    installed: true
    wait: true
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["apply", "-f", "https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.crds.yaml"]
      - events: ["postsync"]
        command: "kubectl"
        args: ["apply", "-f", "cert-manager.yaml"]
    needs:
      - nginx-ingress/nginx-stable

  - name: harbor
    namespace: harbor
    createNamespace: true
    chart: harbor/harbor
    version: 1.9.3
    installed: true
    values:
      - harbor.yaml
    needs:
      - cert-manager/cert-manager

  - name: nginx-stable
    namespace: nginx-ingress
    createNamespace: true
    chart: nginx-stable/nginx-ingress
    installed: true
    wait: true
