apiVersion: v1
kind: Pod
metadata:
  name: webservice
  labels: 
    application: nginx
spec:
  containers:
  - name: webservice
    image: serg2/webservice-demo:1.0
    volumeMounts:
      - name: app
        mountPath: /app
  initContainers:
  - name: init-webservice
    image: busybox:1.28
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
